version: "3.8"
services:
  rasa:
    image: "rasa/rasa:latest"
    expose:
      - 5005
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  rasa-arm:
    image: "koenvervloesem/rasa:latest"
    expose:
      - 6005
    ports:
      - 6005:6005
    volumes:
      - ./:/app
    command:
      - run
