version: '3'
services:
  rasa:
    image: "${SRC}/rasa:1.10.16"
    container_name: rasa
    expose:
      - 5005
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command:
      - run
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: nginx
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - rasa
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --non-interactive --webroot --webroot-path=/var/www/html --email csaicalpoly@gmail.com --agree-tos --no-eff-email -d swanton.calpolycsai.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/html
      o: bind
networks:
  app-network:
    driver: bridge

